### ISSUE TITLE
Dependency not being shaded causes plugin to crash on startup

### ISSUE THREAD

**Issue by Pablete1234** [xxyy/intake-spigot#5]
You are using `UserException` without it being shaded inside intake-spigot (it's part of xyc-api)

```
java.lang.NoClassDefFoundError: li/l1t/common/exception/UserException
        at li.l1t.common.intake.i18n.translators.DefaultTranslators.registerXYCIntakeExceptionsWith(DefaultTranslators.java:63) ~[?:?]
        at li.l1t.common.intake.i18n.translators.DefaultTranslators.registerAllWith(DefaultTranslators.java:52) ~[?:?]
        at li.l1t.common.intake.i18n.ErrorTranslator.<init>(ErrorTranslator.java:38) ~[?:?]
        at li.l1t.common.intake.CommandsManager.<init>(CommandsManager.java:69) ~[?:?]
        at me.pablete1234.plugin.TestPlugin.onEnable(TestPlugin.java:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: li.l1t.common.exception.UserException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
```

**Comment by jonahseguin** [comment]
What version are you using?

**Comment by Pablete1234** [comment]
https://ci.l1t.li/job/public~intake-spigot/lastRelease/ 

4.2.34

**Comment by jonahseguin** [comment]
I do not get this error.  Try re-compiling?  I frequently get NoClassDefFoundErrors when something goes weird with building

**Comment by jonahseguin** [comment]
Try using it as a shaded jar instead of a plugin?

**Comment by Pablete1234** [comment]
Thay won't work.
The plugin is using a class that belongs to xyc-api, but that isn't being shaded into this plugin, and if it works for you it's likely that any other plugin that you have loaded on your server has shaded xyc-api.
A workarround that worked for me was "manually shading" (aka, copy-pasting from one .jar to another) xyc-api into intake-spigot.

**Comment by literalplus** [comment]
This plugin generates two artifacts. One (`intake-spigot.jar`) includes only the source code, the other also includes the libraries (`intake-spigot-...-plugin.jar`), for use in Production. (Hence the name, "plugin" means you can drop it into the plugins folder)

Use the other one.

https://ci.l1t.li/job/public~intake-spigot/

**Comment by Pablete1234** [comment]
That IS the one i was using, it still doesn't shade xyc-api regardless. The pom.xml is configured to shade intake, but NOT xyc-api.

**Comment by literalplus** [comment]
Sorry, you are entirely right. I never noticed this issue because when I used the plugin, I always had other plugins requiring XYC anyways. I find it quite strange that nobody noticed this.

I've updated the readme with a clarification and added an additional artifact to the build. Try this one: https://ci.l1t.li/job/public~intake-spigot/213/ (Note that this also includes an unrelated change from another issue, so if something else breaks, that's probably the cause)

Please report back on whether this fixes your issue.

**Comment by literalplus** [comment]
While testing another unrelated change, I found an issue with the fix and, while I was at it, verified that it actually works now. It does. The first working build is: https://ci.l1t.li/job/public~intake-spigot/216/
